{
 "title": "SQlite Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Database overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Random usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT substr(user_name, 1, 16), random_usage as \"Random Usage\" FROM users ORDER BY random_usage DESC LIMIT 10;",
     "rawQueryText": "SELECT substr(user_name, 1, 16), random_usage as \"Random Usage\" FROM users ORDER BY random_usage DESC LIMIT 10;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Commands over time",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT sum(random_usage) as \"/random commands over time\", sum(dem_usage) as \"/dem commands over time\" FROM users",
     "rawQueryText": "SELECT sum(random_usage) as \"/random commands over time\", sum(dem_usage) as \"/dem commands over time\" FROM users",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Dem usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT substr(user_name, 1, 16), dem_usage as \"Dem Usage\" FROM users ORDER BY dem_usage DESC LIMIT 10;",
     "rawQueryText": "SELECT substr(user_name, 1, 16), dem_usage as \"Dem Usage\" FROM users ORDER BY dem_usage DESC LIMIT 10;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Percentage of used commands",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT SUM(dem_usage) as \"Dem usage\", SUM(random_usage) as \"Random Usage\" FROM users;",
     "rawQueryText": "SELECT SUM(dem_usage) as \"Dem usage\", SUM(random_usage) as \"Random Usage\" FROM users;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}